# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  lua_config = debug
  Webserv_config = debug

else ifeq ($(config),release)
  lua_config = release
  Webserv_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := lua Webserv

.PHONY: all clean help $(PROJECTS) Core Vendor

all: $(PROJECTS)

Core: Webserv

Vendor: lua

lua:
ifneq (,$(lua_config))
	@echo "==== Building lua ($(lua_config)) ===="
	@${MAKE} --no-print-directory -C vendor/scripts -f Makefile config=$(lua_config)
endif

Webserv: lua
ifneq (,$(Webserv_config))
	@echo "==== Building Webserv ($(Webserv_config)) ===="
	@${MAKE} --no-print-directory -C project -f Makefile config=$(Webserv_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendor/scripts -f Makefile clean
	@${MAKE} --no-print-directory -C project -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lua"
	@echo "   Webserv"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"