yaml:
  run_tests: false
socket:
  max_connections: 64
  # in milliseconds
  keep_alive_timeout: 60000
  #! DEPRECATED, AT -1 BREAKS CGI TIMEOUT  
  # in milliseconds
  poll_timeout: 1000
  # in bytes
  read_buffer_size: 65536
  # in bytes
  write_buffer_size: 65536
http:
  # in bytes (100MB)
  max_body_size: 100000000
  # in bytes
  max_uri_size: 4096
  # all HTTP status codes in a map
  error_pages:
    500: config/bin/error_pages/500.html
    404: config/bin/error_pages/404.html
  status_codes:
    100: Continue
    101: Switching Protocols
    102: Processing
    103: Early Hints
    200: OK
    201: Created
    202: Accepted
    203: Non-Authoritative Information
    204: No Content
    205: Reset Content
    206: Partial Content
    207: Multi-Status
    208: Already Reported
    226: IM Used
    300: Multiple Choices
    301: Moved Permanently
    302: Found
    303: See Other
    304: Not Modified
    305: Use Proxy
    306: Switch Proxy
    307: Temporary Redirect
    308: Permanent Redirect
    400: Bad Request
    401: Unauthorized
    402: Payment Required
    403: Forbidden
    404: Not Found
    405: Method Not Allowed
    406: Not Acceptable
    407: Proxy Authentication Required
    408: Request Timeout
    409: Conflict
    410: Gone
    411: Length Required
    412: Precondition Failed
    413: Payload Too Large
    414: URI Too Long
    415: Unsupported Media Type
    416: Range Not Satisfiable
    417: Expectation Failed
    418: "I'm a teapot"
    421: Misdirected Request
    422: Unprocessable Entity
    423: Locked
    424: Failed Dependency
    425: Too Early
    426: Upgrade Required
    428: Precondition Required
    429: Too Many Requests
    431: Request Header Fields Too Large
    451: Unavailable For Legal Reasons
    500: Internal Server Error
    501: Not Implemented
    502: Bad Gateway
    503: Service Unavailable
    504: Gateway Timeout
    505: HTTP Version Not Supported
    506: Variant Also Negotiates
    507: Insufficient Storage
    508: Loop Detected
    510: Not Extended
    511: Network Authentication Required
  mime_types:
    # any
    __any__: text/plain
    __default__: application/octet-stream
    html: text/html
    css: text/css
    js: application/javascript
    json: application/json
    jpg: image/jpeg
    jpeg: image/jpeg
    png: image/png
    gif: image/gif
    svg: image/svg+xml
    ico: image/x-icon
    txt: text/plain
    pdf: application/pdf
    mp3: audio/mpeg
    mp4: video/mp4
    ogg: audio/ogg
    ogv: video/ogg
    oga: audio/ogg
    webm: video/webm
    weba: audio/webm
    wav: audio/wav
    woff: font/woff
    woff2: font/woff2
    ttf: font/ttf
    eot: application/vnd.ms-fontobject
    otf: font/otf
    rar: application/x-rar-compressed
    zip: application/zip
    tar: application/x-tar
    gz: application/gzip
    bz: application/x-bzip
    bz2: application/x-bzip2
    7z: application/x-7z-compressed
    exe: application/x-msdownload
    psd: image/vnd.adobe.photoshop
    ai: application/postscript
    eps: application/postscript
    ps: application/postscript
    xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    xls: application/vnd.ms-excel
    docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
    doc: application/msword
    pptx: application/vnd.openxmlformats-officedocument.presentationml.presentation
    ppt: application/vnd.ms-powerpoint
  static:
    default_index: index.html
    directory_builder_template: config/bin/directory_listing_template.html
    # how many chunks to divide the file into when sending with Transfer-Encoding: chunked
    file_chunks: 10
    # if the file size is not known, how many bytes to read at a time
    file_chunk_size: 1024
  cgi:
    # in milliseconds
    timeout: 60000
misc:
  # levels:
  #  -1: off
  #   0: debug
  #   1: info
  #   2: warning
  #   3: error
  log_level: 1
  name: 'webserv/1.0'
  default_config_file: config/tests/v2/example.yaml
